# Generated by Django 3.2.6 on 2022-04-03 19:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=2048)),
                ('summary', models.CharField(max_length=1024)),
                ('icon', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=2048)),
                ('summary', models.CharField(max_length=1024)),
                ('steps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), size=None)),
                ('village', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='village.village')),
            ],
        ),
    ]
