# Generated by Django 3.2.6 on 2022-04-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='image',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
