# Generated by Django 3.2.6 on 2022-04-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0003_exercise_portainer_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='portainer_ip',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='portainer_link',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='portainer_stack_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
