# Generated by Django 3.2.6 on 2022-05-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0004_auto_20220405_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='portainer_jwt',
            field=models.CharField(blank=True, default=None, max_length=4096, null=True),
        ),
    ]
