# Generated by Django 3.2.6 on 2022-05-24 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('malware_name', models.CharField(max_length=24)),
                ('category', models.CharField(max_length=24)),
                ('group', models.CharField(max_length=24)),
                ('investigator_name', models.CharField(max_length=24)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportFilesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=24)),
                ('hash', models.CharField(max_length=24)),
                ('notes', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reportmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReportConnectionsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_ip', models.CharField(max_length=24)),
                ('notes', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reportmodel')),
            ],
        ),
    ]
