# Generated by Django 3.2.6 on 2022-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20220524_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconnectionsmodel',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportconnectionsmodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportconnectionsmodel',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
