# Generated by Django 3.2.6 on 2022-05-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20220524_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfilesmodel',
            name='file',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='reportfilesmodel',
            name='hash',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='reportfilesmodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
