# Generated by Django 3.2.6 on 2022-05-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20220524_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconnectionsmodel',
            name='ip',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
