# Generated by Django 3.2.6 on 2022-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_reportconnectionsmodel_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconnectionsmodel',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportfilesmodel',
            name='file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='reportfilesmodel',
            name='hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='category',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='group',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='investigator_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='malware_name',
            field=models.CharField(max_length=256),
        ),
    ]
