# Generated by Django 3.2.6 on 2022-05-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20220526_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconnectionsmodel',
            name='notes',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='reportconnectionsmodel',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='reportfilesmodel',
            name='notes',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='summary',
            field=models.TextField(max_length=2048),
        ),
    ]
